### ISSUE TITLE
criação de histórico para os cálculos já efetuados

### ISSUE THREAD

**Issue by gustavo8555** [Felipereisbarreto/Calculadora-CFC#1]
Olá @Felipereisbarreto,
Tenho um pequeno estabelecimento, para comercialização de pães (também conhecido como padaria).

E gostaria de utilizar sua calculadora, no entanto tenho problemas de memória.

Você poderia incluir um histórico dos últimos cálculos feitos?

Boa tarde!

**Comment by Felipereisbarreto** [comment]
Seus problemas acabaram, está implementado diretamente para o senhor um histórico na mais nova versão da Calculadora_CFC disponível para download em todas as plataformas!

**Comment by gustavo8555** [comment]
Muito obrigado meu caro
